media:
  input: public/images
  output: /images

content:
  - name: recipes
    label: Recipes
    type: collection
    path: src/content/recipes
    format: yaml-frontmatter
    filename: "{primary}.md"
    view:
      fields: [title, date, published, "tags[0]"]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: heroImage
        label: Hero Image (URL or local path)
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: servings
        label: Servings
        type: number
      - name: prepTimeMins
        label: Prep Time (mins)
        type: number
      - name: cookTimeMins
        label: Cook Time (mins)
        type: number
      - name: totalTimeMins
        label: Total Time (mins)
        type: number
      - name: ingredients
        label: Ingredients
        type: text
        list: true
        required: true
      - name: steps
        label: Steps
        type: text
        list: true
        required: true
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
